package com.diary.backend.Enums;

public enum DiaryStatus {
    SUCESS,
    INVALID_DIARY_DATE,
    INVALID_USER_ID,
    INVALID_LATITUDE_OR_LONGITUDE,
    API_PROCESSING_ERROR,
    INVALID_DIARY_CONTEXT,
    API_RESPONSE_COVERT_ERROR,
    DIARY_REGISTER_ERROR,


}
